sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.6

install:
  # Install Jekyll and dependencies
  - bundle install

before_script:
  - git config --global user.email "dpwl7953@gmail.com"
  - git config --global user.name "YeJi Shin"

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "UbWtDbwSSCHTim6MX92NRikmnebRRIHvqZKzuMyPNXzmmq9ACxDJFqaV4ZfefuixdK7CB5AOPzlAPdib+n6xawsN1UejvbsKiQqFD0T/8GPUDgi/PHaoC
8XmryvbYP5f7lKIN7ph8BTzFITfk0ZT1qeOgdJHixYXlu2y/rTm2jXbLHNghkn3X3hbf6ChmDFs/pDAycdLdwdBQfKJflU2yL5Ii36BdgpTgohY7STpuieRzEOI5D3Ev
d/gZzKUuDwUGE0DVZilsWQ5Tzorbm6oHFcWyCIxmxj2GGbiPdhnLyAuENKROhLiiObwjx+dPm1YIkndG6UgrqvF7HOeDmq7/LnKJ4XwCukzGxoklW3RU2AKxrAxzuFSo
ADbvbSBdR16XtaTHzUtRSFs/N2aOLmaWAahqThZK9qpWQ1fvztbWDSoOh7ijpcpZgFfeSGAyZj7wDvfDFTIgsLCopH/RBNsl31R0jUkJ55AHuSP9o6anWqz1qbgL/27Q
Lt3sBO9Wju/iLItZs7cl16vdjDE2IzFCALBBgmtmxlLNX9BVJjbnGrrFF6vpRgvjKath/8bbyzK0+CIhHUFxgNzFHg4B+FgbO4iXmngeIcgCZTlKEF/SO833MubEKjdV
fJ1pLfzv6+TdsNYgjKagGV2DBzvLMIa+ZKRakNihohAc1rEAsRFTjw="
branches:
  only:
    - master